# Generated by Django 5.1.3 on 2024-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sku', models.IntegerField()),
            ],
        ),
    ]
